import { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowRight } from "lucide-react"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

interface Section {
  heading: string
  paragraphs: string[]
}

interface Post {
  slug: string
  category: string
  title: string
  excerpt: string
  date: string
  readTime: string
  sections: Section[]
}

const posts: Post[] = [
  {
    slug: "geo-for-b2b-india",
    category: "Search & AI Visibility",
    title: "What Is Generative Engine Optimisation (GEO) and Why Every B2B Business in India Needs It Now",
    excerpt:
      "AI-generated answers are becoming a buying surface. GEO makes your brand easier for answer engines to understand, cite, and trust.",
    date: "2026-05-01",
    readTime: "8 min read",
    sections: [
      {
        heading: "Search just changed. Most businesses haven't noticed yet.",
        paragraphs: [
          "When a procurement manager in Pune wants to find a compliance automation vendor, they no longer start with a Google search. They open ChatGPT and type: \"Which AI agency in India can help us automate GST compliance reminders?\" The answer they get is generated by the model — curated, opinionated, and delivered without a single click to your website.",
          "That is the shift. And it happened fast. AI Overviews now appear in over 13% of Google queries. Perplexity and ChatGPT together handle hundreds of millions of searches per week. Gemini is embedded in every Google Workspace account. The buying journey for B2B services has a new first step — and most businesses aren't in that conversation at all.",
          "Generative Engine Optimisation (GEO) is the discipline of making your brand visible, credible, and correctly understood inside AI-generated answers.",
        ],
      },
      {
        heading: "How AI engines decide what to cite",
        paragraphs: [
          "Unlike traditional search, where ranking is determined by page authority and keyword relevance, AI citation is determined by a different set of signals: What does the model already know about your brand? What sources does it trust? How authoritative and consistent is the information it finds about you across the web?",
          "AI engines like ChatGPT and Perplexity pull from training data, real-time web search (for models with browsing), Reddit threads, Quora answers, Wikipedia, industry publications, and curated directory listings. If your brand appears positively, accurately, and frequently across these sources — you get cited. If you don't, you don't exist.",
          "The model is not ranking your website. It is forming an opinion about your brand based on everything it has ever read about you. GEO is the work of influencing that opinion.",
        ],
      },
      {
        heading: "What GEO actually involves",
        paragraphs: [
          "GEO is not a single tactic. It is a multi-channel programme with five main components. First, your website must be readable by AI crawlers — which means llms.txt configuration, semantic HTML, proper entity schema, and server-side rendering for pages that currently rely on JavaScript.",
          "Second, your content must be structured to be cited — answer-first writing, FAQ schema, clear entity definitions, and proprietary data or research that AI models can attribute to you specifically.",
          "Third, your brand must have authoritative external presence — expert commentary in industry publications, verified Wikipedia and Wikidata entities, a strong LinkedIn company page, G2 and Capterra listings, and Reddit participation in relevant communities. These are the sources AI models draw from when forming brand-level opinions.",
          "Fourth, you need to monitor for hallucination — cases where AI models describe your company inaccurately or attribute competitor products to you. This happens, and the fix requires structured data correction and source remediation.",
          "Fifth, you need measurement — AI visibility reporting that tracks citation frequency per prompt category, sentiment in AI responses, and competitor share of voice across ChatGPT, Perplexity, Gemini, and Claude.",
        ],
      },
      {
        heading: "Why Indian B2B businesses need GEO now",
        paragraphs: [
          "The reason GEO is particularly urgent for Indian B2B businesses right now is timing. The AI search market is not yet saturated with high-quality, AI-readable content in Indian B2B contexts. Most Indian service businesses have no llms.txt, no entity schema, no Wikipedia presence, and no structured presence on AI-cited platforms.",
          "This is a brief window where early movers can establish citation authority before AI models have strong opinions about who leads in each category. Once those opinions are formed — once ChatGPT consistently recommends three or four vendors in your space — the window largely closes.",
          "The businesses building GEO programmes today are the ones that will appear in AI-generated shortlists in 2027. The ones that wait are the ones that will spend 2027 trying to figure out why their leads have dried up.",
        ],
      },
      {
        heading: "Where to start",
        paragraphs: [
          "If you are starting from zero, the right sequence is: AI readiness audit first (can AI crawlers even read your site?), then entity and schema cleanup, then content restructuring for AI citation, then off-site brand signal building across AI-indexed platforms.",
          "The full programme takes months to show results — but the audit and remediation work can be completed quickly and shows immediate improvement in AI crawler access and structured data accuracy.",
        ],
      },
    ],
  },
  {
    slug: "rag-for-ca-firms-india",
    category: "Knowledge & Applied AI",
    title: "RAG Systems for CA Firms in India: How to Build an AI Layer Over Your Compliance Data",
    excerpt:
      "A custom RAG system turns scattered PDFs, circulars, emails, and internal notes into a searchable AI layer with source-backed answers.",
    date: "2026-04-18",
    readTime: "10 min read",
    sections: [
      {
        heading: "The knowledge problem in every CA firm",
        paragraphs: [
          "In a mid-sized CA firm in India, institutional knowledge lives in a hundred different places. GST circulars are downloaded and saved in a shared folder that no one has organised. Income tax notifications arrive by email and get forwarded around. Internal working notes from senior partners sit in Word documents on individual laptops. Standard responses to common client queries are stored in a senior staff member's memory.",
          "When a junior associate needs to answer a client question about a GST ruling from two years ago, they either spend forty minutes searching, ask a senior who is usually in a meeting, or — worst of all — guess. The knowledge exists. It just isn't accessible.",
          "This is not a technology problem. It is an information architecture problem. And a custom RAG system is the most direct solution to it.",
        ],
      },
      {
        heading: "What a RAG system is and why it's different from a chatbot",
        paragraphs: [
          "RAG stands for Retrieval-Augmented Generation. A RAG system combines a retrieval layer (which searches your documents) with a generation layer (which produces answers in natural language). The key property that separates it from a standard AI chatbot is grounding — every answer the system generates is anchored to a specific source document that you provided.",
          "When a staff member asks 'What is the GST rate for restaurant services for the current financial year?' — the RAG system does not guess based on its training data. It searches your indexed corpus of GST circulars, retrieves the relevant notification, and generates an answer with a direct citation to the source document.",
          "This source-grounding is essential in a CA context. The consequence of an inaccurate answer is professional liability. A hallucinating chatbot is worse than no chatbot at all. A well-built RAG system with confidence scoring and source attribution is safer than an internet search.",
        ],
      },
      {
        heading: "What documents go into a CA firm RAG system",
        paragraphs: [
          "The document corpus for a CA firm RAG system typically includes: GST circulars and notifications from the CBIC, income tax circulars and CBDT notifications, ICAI guidance notes and standards, internal audit and filing checklists, client-specific working notes, prior-year ITR and GST return summaries, and firm-specific procedure documents.",
          "The ingestion process involves parsing each document type (PDFs, Word files, emails, Excel sheets), chunking them into sections the retrieval system can match against, generating vector embeddings for semantic search, and indexing them in a vector database. The system also supports hybrid retrieval — combining semantic search with keyword search — so that specific regulatory section numbers or circular references are found even when the semantic context is ambiguous.",
        ],
      },
      {
        heading: "The build process in practice",
        paragraphs: [
          "A typical CA firm RAG deployment takes six to eight weeks. The first two weeks are spent on document audit and ingestion pipeline design — figuring out what exists, where it lives, and how to parse it correctly. The middle weeks cover retrieval pipeline configuration, embedding model selection, and testing accuracy against a set of representative queries from the firm.",
          "The final phase covers the interface layer — usually a WhatsApp bot for firm staff or a web interface, depending on the firm's preference — and access control setup so that different staff levels see different document scopes.",
          "After deployment, the system requires monthly maintenance: new circulars need to be ingested, query logs need to be reviewed for gaps, and the retrieval accuracy needs to be monitored as the document corpus grows.",
        ],
      },
      {
        heading: "What changes after deployment",
        paragraphs: [
          "The most consistent feedback from CA firms that have deployed RAG systems is not about speed — it is about confidence. Junior staff stop guessing. Senior partners stop being interrupted by routine knowledge queries. Clients get faster, more consistent answers.",
          "The second-order effect is institutional knowledge preservation. When a senior partner retires or a key staff member moves on, their knowledge — which previously existed only in their head or their personal files — is captured in the system and remains accessible to the firm.",
          "The third effect is query logging. Every question that cannot be answered by the system surfaces as a knowledge gap. This creates a natural prioritisation mechanism for knowledge base expansion — the firm knows exactly what it is missing.",
        ],
      },
    ],
  },
  {
    slug: "agentic-vs-chatbot-vs-workflow",
    category: "Agentic Automation",
    title: "The Difference Between a Chatbot, a Workflow Tool, and an Agentic System",
    excerpt:
      "Chatbots answer. Workflow tools connect. Agentic systems decide, use tools, escalate edge cases, and complete operational work.",
    date: "2026-04-05",
    readTime: "7 min read",
    sections: [
      {
        heading: "Three tools that look similar but are fundamentally different",
        paragraphs: [
          "Most businesses that have tried to automate in the past five years have used one of three things: a chatbot, a workflow tool like Zapier or Make, or an AI agent. These three categories get conflated constantly — in vendor pitches, in trade press, and in internal discussions about automation strategy.",
          "The confusion is expensive. Businesses buy chatbots expecting agents. They build Zapier flows expecting intelligence. They commission expensive agent deployments for tasks that a simple trigger-action automation would have handled fine. Getting the categories right is a prerequisite for spending the right budget in the right place.",
        ],
      },
      {
        heading: "What a chatbot actually is",
        paragraphs: [
          "A chatbot is an interface. It takes a message, matches it to a pattern or intent, and returns a pre-defined or generated response. A chatbot can be scripted (decision-tree based) or AI-powered (LLM-based). The key property is that a chatbot's job ends at the response — it answers and waits.",
          "A good chatbot is valuable for high-volume FAQ handling, tier-1 customer support deflection, and lead qualification screening. A bad chatbot frustrates users by pretending to understand things it doesn't. The right chatbot deployment has a clear scope definition, a tested escalation path, and an honest fallback when the query is outside scope.",
          "Most businesses that say they've 'tried AI' have tried a chatbot. Most businesses that say 'AI doesn't work' built a chatbot with too broad a scope.",
        ],
      },
      {
        heading: "What a workflow automation tool does",
        paragraphs: [
          "A workflow tool like n8n, Make, or Zapier automates trigger-action sequences. An event happens (a form is submitted, an email arrives, a CRM field changes), and the tool executes a defined sequence of steps in response (send a WhatsApp message, update a record, add a row to a sheet, generate a document).",
          "Workflow tools are deterministic. They don't reason — they execute. They are excellent for connecting systems, eliminating repetitive data-entry tasks, and automating structured processes where the logic is clear and the inputs are predictable.",
          "The limitation of workflow tools is that they fail ungracefully when inputs are unexpected. If a lead form has an unusual field value, if an email contains a format the tool wasn't built for, or if an API returns an unexpected response — the workflow either errors out or silently produces wrong output. There is no judgement involved.",
        ],
      },
      {
        heading: "What an agentic system is",
        paragraphs: [
          "An agentic system is software that can reason, plan, use tools, and complete multi-step goals — without being given explicit step-by-step instructions for every situation it encounters. An agent is given a goal ('collect all outstanding compliance documents from clients who have not submitted by the deadline') and a set of tools (WhatsApp API, CRM read/write access, document storage) and then figures out the sequence of actions required.",
          "The defining properties of an agent are: it can handle novel situations; it can use external tools programmatically; it can loop, backtrack, and retry; and it can escalate to a human when it encounters something outside its confidence threshold.",
          "An agentic system is not appropriate for simple, well-defined tasks. If the logic is clear and the inputs are predictable, a workflow tool is faster and cheaper. Agents are appropriate when: the task requires reading unstructured inputs (emails, documents, voice), the sequence of steps depends on intermediate results, or edge cases are frequent enough that a human-in-the-loop design is necessary.",
        ],
      },
      {
        heading: "How to choose which to use",
        paragraphs: [
          "Start with the task. If it is answer-a-question, use a chatbot (possibly with a RAG backend for accuracy). If it is connect-system-A-to-system-B on a trigger, use a workflow tool. If it is complete-a-complex-multi-step-process-with-variable-inputs, use an agent.",
          "Most real automation programmes end up using all three in combination. A WhatsApp chatbot handles inbound queries and routes them. A workflow tool creates CRM records and sends confirmation messages. An agent handles the exceptions — the cases where the standard flow doesn't apply and a decision needs to be made.",
          "The businesses that get the most value from AI are the ones that deploy the right tool at each layer — not the ones that try to solve every problem with the same category of software.",
        ],
      },
    ],
  },
  {
    slug: "aeo-seo-geo-explained-india",
    category: "Search & AI Visibility",
    title: "AEO vs SEO vs GEO: A Clear Breakdown for Indian Business Owners",
    excerpt:
      "SEO gets you discovered in search results. AEO structures direct answers. GEO builds visibility inside AI-generated recommendations.",
    date: "2026-03-22",
    readTime: "9 min read",
    sections: [
      {
        heading: "There is now more than one kind of search visibility",
        paragraphs: [
          "Three years ago, if your business appeared on the first page of Google for your target keywords, you had solved the visibility problem. Today, buyers have three distinct channels through which they discover and evaluate vendors: traditional search results (ranked links), direct answer boxes and AI Overviews within Google, and fully AI-generated answers in ChatGPT, Perplexity, and Gemini.",
          "Each of these channels is different. Each rewards different content and infrastructure. And each requires a different optimisation discipline. Understanding the three — SEO, AEO, and GEO — is the starting point for building a search visibility strategy that works in 2026.",
        ],
      },
      {
        heading: "SEO: Visibility in ranked results",
        paragraphs: [
          "Search Engine Optimisation is the oldest of the three. The goal is to appear in the ranked list of results when a user searches a specific query. The mechanisms are: technical site health (crawlability, page speed, schema markup), content quality and topical authority (depth, accuracy, relevance to search intent), and link authority (how many credible sites link to you).",
          "SEO remains essential because most search journeys still begin with Google, and the ranked results still receive significant click-through — particularly for informational and navigational queries. Even in a world of AI Overviews, branded searches, product comparison searches, and local searches still heavily favor traditional ranked results.",
          "The risk of pure SEO focus today is that it optimises for visibility in a channel that is shrinking as a percentage of total discovery — particularly for high-intent B2B queries where AI-generated answers are increasingly the first response.",
        ],
      },
      {
        heading: "AEO: Visibility in direct answers",
        paragraphs: [
          "Answer Engine Optimisation is the practice of structuring your content to be selected as the direct answer to a specific question. This covers featured snippets (the block of text above ranked results), People Also Ask boxes, AI Overviews within Google, and Knowledge Panels.",
          "The mechanisms are different from traditional SEO: content must lead with the answer (not bury it in the body), FAQ schema must be implemented correctly, answers must be compressed to 40-60 words for snippet eligibility, and headings must match the question format of search queries.",
          "AEO is particularly valuable for B2B businesses because the questions that trigger featured snippets and AI Overviews — 'What is the GST rate for...', 'How do I automate...', 'What is the difference between...' — are often the exact queries that buyers ask when evaluating options. Appearing as the direct answer to a category question builds brand authority even when no click occurs.",
        ],
      },
      {
        heading: "GEO: Visibility in AI-generated recommendations",
        paragraphs: [
          "Generative Engine Optimisation is the newest and, for many businesses, the least understood of the three. The goal is to ensure that when someone asks ChatGPT, Perplexity, Gemini, or Claude a question in your category — 'What are the best AI agencies in India for CA firms?' — your brand appears in the generated response.",
          "Unlike SEO and AEO, GEO does not primarily optimise your website. It optimises your brand's external presence across the sources that AI models draw from — Wikipedia, Reddit, industry publications, G2, Capterra, Quora, and Wikidata. AI models form opinions about brands based on everything they have read about them. GEO is the work of making that opinion accurate and positive.",
          "The second component of GEO is content strategy — structuring your own content so that it is citable. This means original research and data that can be attributed to you, clear entity definitions, and content that directly answers the prompts your buyers ask AI systems.",
        ],
      },
      {
        heading: "How the three compound together",
        paragraphs: [
          "The businesses that win at search visibility in 2026 do not treat SEO, AEO, and GEO as competing strategies. They treat them as layered systems. A well-ranked page (SEO) that also wins the featured snippet for its target query (AEO) and is cited by AI models as an authoritative source in the category (GEO) captures visibility at every stage of a buyer's discovery journey.",
          "For Indian B2B businesses, the practical starting point is: audit your current SEO health, identify the high-value questions where you should be winning AEO positions, and begin the GEO groundwork — entity cleanup, llms.txt, and external brand signal building — before the AI citation market in your category reaches saturation.",
          "The window for first-mover advantage in GEO is real, and it is closing. The businesses building these systems now will be significantly harder to displace in twelve months than they are today.",
        ],
      },
    ],
  },
]

export function generateStaticParams() {
  return posts.map((p) => ({ slug: p.slug }))
}

interface Props {
  params: Promise<{ slug: string }>
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params
  const post = posts.find((item) => item.slug === slug)

  return {
    title: post ? `${post.title} | Kynato Insights` : "Insight | Kynato",
    description: post?.excerpt,
    alternates: {
      canonical: `https://kynato.com/insights/${slug}`,
    },
  }
}

export default async function InsightDetailPage({ params }: Props) {
  const { slug } = await params
  const post = posts.find((item) => item.slug === slug)

  if (!post) return notFound()

  return (
    <div className="min-h-screen flex flex-col bg-black selection:bg-accent-teal/30 selection:text-white">
      <Navbar />
      <main className="flex-1 pt-24">
        <article>
          {/* Hero */}
          <section className="py-20 md:py-28 border-b border-white/5 bg-[#09090B] relative overflow-hidden">
            <div className="absolute top-0 left-0 w-[600px] h-[400px] bg-[#027C88] opacity-[0.03] blur-[120px] rounded-full pointer-events-none" />
            <div className="container mx-auto px-4 max-w-4xl relative z-10">
              <Link href="/insights" className="inline-block mb-4 text-sm font-semibold text-accent-teal hover:underline">
                ← Insights
              </Link>
              <div className="mb-5 flex flex-wrap gap-3 text-xs text-muted-foreground">
                <span className="font-bold uppercase tracking-widest text-accent-teal">{post.category}</span>
                <span>{post.readTime}</span>
                <span>
                  {new Date(post.date).toLocaleDateString("en-IN", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                  })}
                </span>
              </div>
              <h1 className="font-urbanist font-black text-4xl sm:text-5xl md:text-6xl text-white mb-6 leading-tight">
                {post.title}
              </h1>
              <p className="font-roboto text-[#D0D5DD] text-lg md:text-xl leading-relaxed max-w-3xl">
                {post.excerpt}
              </p>
            </div>
          </section>

          {/* Article body */}
          <section className="py-20 bg-black">
            <div className="container mx-auto px-4 max-w-3xl">
              <div className="space-y-12">
                {post.sections.map((section) => (
                  <div key={section.heading}>
                    <h2 className="font-urbanist font-bold text-2xl md:text-3xl text-white mb-5 leading-snug">
                      {section.heading}
                    </h2>
                    <div className="space-y-4">
                      {section.paragraphs.map((para, i) => (
                        <p key={i} className="font-roboto text-[#D0D5DD] text-base md:text-lg leading-relaxed">
                          {para}
                        </p>
                      ))}
                    </div>
                  </div>
                ))}
              </div>

              {/* CTA */}
              <div className="mt-16 border border-white/5 bg-[#09090B] rounded-2xl p-8">
                <p className="font-urbanist font-bold text-xl text-white mb-3">
                  Want to discuss this with Kynato?
                </p>
                <p className="font-roboto text-muted-foreground mb-6 leading-relaxed">
                  Book a 30-minute strategy call. We will map your specific situation and show you what the right system looks like in your context.
                </p>
                <Link
                  href="/strategy"
                  className="inline-flex items-center text-accent-teal font-semibold hover:underline"
                >
                  Book a Strategy Call <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </div>
            </div>
          </section>

          {/* Back to insights */}
          <div className="border-t border-white/5 bg-[#09090B] py-10">
            <div className="container mx-auto px-4 max-w-3xl">
              <Link href="/insights" className="inline-flex items-center text-sm font-semibold text-muted-foreground hover:text-accent-teal transition-colors">
                ← Back to all insights
              </Link>
            </div>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  )
}
